### PR TITLE
update version to v1.0.2

### PR DESCRIPTION
**Pull request by grlee77**

### CODE REVIEW

**Comment by rgommers** [comment]
The Cython pin for readthedocs is still on 0.20.2 and just failed: https://readthedocs.org/projects/pywavelets/builds/8655136/. Maybe good to include a version bump in this PR?

**Comment by grlee77** [comment]
right, I did not backport that RTD fix to the 1.0.x branch. I can do that over at the main repo and retag 1.0.2.

everything on Travis is failing here too, so probably something in this repo has become out of date as well

**Comment by rgommers** [comment]
that sounds like a good plan

**Comment by grlee77** [comment]
still waiting on CI to retag v1.0.2 at the main repo. 

Hopefully just updating the `multibuild` submodule here will fix the Travis failures. I

**Pull request merged**
