### PR TITLE
bump version to 0.5.2

### PR DESCRIPTION
**Pull request by grlee77**

### CODE REVIEW

**Comment by grlee77** [comment]
although no longer supported on master, Python 2.6 and 3.3 are nominally still supported in 0.5.2.  I have not modified to build wheels for these as we never did for 0.5.1 and there were no complaints.

**Comment by rgommers** [comment]
Makes sense - not worth spending any effort on 2.6/3.3 at this point.

**Comment by grlee77** [comment]
one other question, @rgommers:
I uploaded the `.tar.gz` sdist to PyPI, but I could not then upload the .zip version as it stated ("Duplicate file upload detected").  not sure if something changed since the last release where they don't allow both formats?  I was using `twine` and have not tried uploading it manually via the web interface.

**Comment by matthew-brett** [comment]
Yes, that's a recent change in pypi - it only allows one of the .zip or .tar.gz formats.

**Comment by grlee77** [comment]
thanks, I suspected as much.
should be ready to merge here.  will update the `conda-forge` recipe now too

**Pull request merged**
