### PR TITLE
add python 3.6 builds on Appveyor

### PR DESCRIPTION
**Pull request by grlee77**
updating to generate Python 3.6 windows wheels for PyPI

### CODE REVIEW

**Comment by matthew-brett** [comment]
Maybe worth updating to latest `multibuild`.

Need to use 1.11.3 numpy wheel for Python 3.6 on Appveyor (no 3.6 wheels for earlier versions).

**Comment by grlee77** [comment]
looks like it was set to use numpy 1.10.4.  will try now with updated `multibuild` and numpy 1.11.3

**Comment by matthew-brett** [comment]
I did the edits I was suggesting above, over at https://github.com/MacPython/pywavelets-wheels/pull/2 - these seem to work.  OK to close this one and merge that one?

**Comment by grlee77** [comment]
sure.  sounds good

**Pull request closed without merging**
