### PR TITLE
bump version to v1.0.0

### PR DESCRIPTION
**Pull request by grlee77**
building wheels for the new PyWavelets release

### CODE REVIEW

**Comment by grlee77** [comment]
It looks like the failures here are due to precision issue on some variants in one of the newer tests.

**Comment by grlee77** [comment]
cc @rogommers:  Should I tag a v1.0.1 just to fix this test case?

**Comment by rgommers** [comment]
I'd just move the v1.0.0 tag in this case. That will not cause any problems.

**Comment by rgommers** [comment]
It should be added to the README of this repo that it's usually best to first push the commit which is the intended final one for the release, then push a pr or commit to this repo which sets `BUILD_COMMIT` to that commit, and only if all wheels are built successfully then push the tag to GitHub. That procedure avoids having to move tags.

**Comment by grlee77** [comment]
I moved the tag then closed and reopened here to see if that resolves the issue

**Comment by grlee77** [comment]
I took Ralf's advice and just moved the tag. With the tolerance in the previously failing test bumped from 1e-6 to 1e-5 we are all green. conda-forge is passing as well. so I am going to merge

**Pull request merged**
